
spring:
  application:
    name: ebuy-gateway
server:
  port: 5000

eureka:
  # 修改实例的ID
  instance:
    instance-id: ebuy-gateway
    # 偏好IP地址设置
    prefer-ip-address: true
  client:
    # 设置与Eureka Server交互地址 服务的注册、服务发现依靠这个地址  http://locahost:6001/eureka
    serviceUrl:
      defaultZone: http://localhost:6000/eureka

zuul:
  # 忽略服务 即该服务不允许使用服务真实名称访问
  # ignoredServices: microservicecloud-item
  ignoredServices: '*'
  # 设置路由
  routes:
    # 路由名称 自定义
    myitem:
      # /myitem/ 下所有请求 调用microservicecloud-item 这个服务
      path: /item/**
      serviceId: EBUY-ITEM
  # 给路由设置前缀
  prefix: /api