server:
  port: 9000

eureka:
  # 修改实例的ID
  instance:
    instance-id: manage-web
    # 偏好IP地址设置
    prefer-ip-address: true
  client:
    # 设置与Eureka Server交互地址 服务的注册、服务发现依靠这个地址  http://locahost:6001/eureka
    serviceUrl:
      defaultZone: http://localhost:6000/eureka/
    register-with-eureka: false

